#  spring:
#    thymeleaf:
#      cache: false
#      check-template: true
#      check-template-location: true
#      enabled: true
#      encoding: UTF-8
#      mode: html
#      prefix: classpath:/templates
#      suffix: .html
#
#    datasource:
#      url: jdc:postgresql://localhost:5433/internet_shop
#      username: postgres
#      password: postgres
#
#      hikari:
#        connection-timeout: 60000
#        maximum-pool-size: 5
#    jpa:
#      hibernate.ddl-auto: update
#      show-sql: true
#      properties.hibernate.temp.use_jdbc_metadata_defaults: false
#
#      database-platform: org.hibernate.dialect.PostgreSQL12Dialect
#
#      loggining:
#        pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg"
#        level:
#          root: WARN
#          org.hibernate:
#            SQL: debug
#            type.description.sql: trace
#          org.springframework.web: DEBUG
#    mvs:
#      view.prefix: /WEB-INF/jap
#      view.suffix: .jsp
#    messages.basename: validation